version: "3.7"

services:

  flask-app:
    build: ./flask-app
    container_name: flask-app
    restart: always
    environment:
      - APP_NAME=WaleFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"